---
- name: Download Gitlab package repository
  become: true
  get_url:
    url: "{{ gitlab_package_url }}"
    dest: /home/{{ os_user }}

- name: Change downloaded file's permission
  become: true
  file:
    path: /home/{{ os_user }}/{{ gitlab_package_url | basename }}
    mode: "0744"

- name: Execute installation script
  become: true
  command: /home/{{ os_user }}/{{ gitlab_package_url | basename }}

- name: Install Gitlab
  become: true
  yum:
    name: gitlab-ee
    state: present

- name: Gitlab reconfiguration
  become: true
  command: gitlab-ctl reconfigure
  changed_when: false

- name: Get password content for installation
  become: true
  command: cat {{ gitlab_pass }}
  register: gitlab_pass
  changed_when: false

- name: Print out password
  debug:
    msg: "{{ gitlab_pass }}"

- name: Enable port 80 for Gitlab service
  become: true
  firewalld:
    port: "80/tcp"
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == "RedHat"

