---
# tasks file for virus

## >>>>>>>>>>> FINAL TESTING >>>>>>>>

- name: VM 1 (Centos7) - Install Gitlab
  hosts: centos1, ubuntu1
  pre_tasks:
    - name: Include global vars
      include_vars: main.yml
  roles:
  - gitlab

- name: "VM 2 - Install Jenkins, Docker, GCloud CLI"
  hosts: centos2, ubuntu2
  pre_tasks:
    - name: Include global vars
      include_vars: main.yml
  roles:
  - jenkins
  - docker
  - gcpcli

- name: "VM 3 - Install Nexus & SonarQube"
  hosts: centos3, ubuntu3
  pre_tasks:
    - name: Include global vars
      include_vars: main.yml
  roles:
  - nexus
  - sonarqube
